String kingsizebed =
    "The Nilkamal Marbito King Bed is a true embodiment of timeless elegance and meticulous craftsmanship. Constructed with Engineered wood, this bed assures enduring reliability, standing the test of time. Its thoughtfully designed storage solution with four spacious compartments and headboard shelves offers efficient organization for your essentials. The accent marble ply in the headboard centre elevates the overall aesthetic, infusing glamour into your bedroom decor. Enhanced with a resistive melamine finish, it increases longevity and simplifies maintenance. The bed's pristine white colour adds an air of neutrality to your bedroom decor, granting you the creative freedom to curate a serene space that reflects your unique style.";
String bunkBed =
    "The top bunk's safety railing is crafted with durability in mind, ensuring it withstands regular use and provides reliable protection for sleepers. Its sturdy construction extends around all sides of the top bunk, offering comprehensive safety to prevent accidental falls during sleep or play. Made from high-quality materials, the railing maintains its structural integrity over time, letting the occupants fall asleep without any worries.";
String sideDrawer =
    "At True Furniture, we pride ourselves on crafting exquisite solid wood furniture that combines timeless design with unmatched durability. Our range includes a variety of finely crafted pieces such as dining sets, coffee tables, shoe racks, cabinet drawers, chests of drawers, and dining chairs. We also offer an array of bedroom and living room furniture, including beds, sofas, almirahs, and bookshelves. Whether you need a sturdy study table or a stylish shoe rack, our furniture is designed to elevate every room in your home with the beauty and strength of natural wood. Choose True Furniture for quality that lasts a lifetime.";
String livingroom4 =
    "NICOBAR Round Center Coffee Table Wooden Teapoy Tea Cocktail Tables Furniture for Home Office Living Room Bedroom Hall.";
String livingroom3 =
    "Past perfect. Inspired by an erstwhile colonial aesthetic, the Malabar range is comfortingly familiar, yet refreshingly new. Designed to pair perfectly with the Malabar sofa and ottoman, this coffee table also works beautifully on its own. The intricate groove detailing on each leg is lovingly carved by hand and is a hallmark of the range. A capacious table top and shelf make room for nibbles, drinks, and remotes. Made from solid mango wood and brass (Amber Walnut) Solid Sheesham wood and brass(Teak) Please refer to images for dimension details Indoor use only";
String livingroom1 =
    "Sheesham wood Bennett sofa set for living room with cushions presents a wide showcase of modern furniture that’s designed to seamlessly blend with your interior’s décor. Crafted for compact homes, the range is clean and convenient. All the collections have an understated design aesthetic that adapts to any space. The designs represent the ideal of cutting excess while manufacturing, each product has gone through a stringent quality checking process in multi-stages, with a checkpoint for multiple quality aspects.";
String livingroom2 =
    "The grain patterns on wood may vary depending on the species and way in which it is sawn – for example, Sheesham is grown across several regions of India, each with unique mineral soil compositions, resulting in grain pattern structures that are just characteristics of the natural beauty of the wood. Some furniture is deliberately aged to give it a more rustic feel. The appearance of timber surfaces will soften and mature over time. The gloss levels on new furniture will initially vary from pieces that were previously purchased.";
String sixSeaterdining =
    "Akira-Hana Solid Wood Sheesham 6 Seater Dining Set With Glass online from Khaticraft that is 100% Authentic Solid Sheesham ,Treated and Seasoned Wood, Free from Termite and Borer, Shipping Time 2 Weeks, Pan India Delivery and Product Comes with Warranty";
String diningbench1 =
    " Elevate your dining experience with the Royaloak Ashoka Wooden Dining Bench – where sheesham wood's charm meets lasting quality and modern allure. Buy wooden dining benches from Royaloak today, and enjoy the benefits of owning international furniture from India’s no.1 furniture brand. Live like a king or a queen, and discover the charm of regal living with Royaloak’s Emperor collection. Inspired by the grand interiors of Indian palaces, this vintage collection is exclusively curated for those who settle for nothing less. Crafted to perfection using solid wood, these fine pieces of furniture will last for generations.";
String glassCabinet1 =
    "Product Dimensions: Length (48 cm), Width (40 cm), Height (168 cm) Primary Material: Sheesham Wood, Base Material: Wood, Back Material: Acacia Wood No Assembly Required: The product is delivered in a pre-assembled state Premium handcrafted construction by the skilled artisans from Churu (Rajasthan) Crafted from high-quality Sheesham wood, known for its durability and rich grain patterns.";
String studydeskwithself =
    "The decent and classy style of this desk is perfect for any space in your home. The functionality is endless with its storage drawers and storage shelf. Whether it is used for a child's desk or an adult writing desk. The wood desk with spacious desktop keeps everything within reach to ensure comfortable working experience. Modish style fits greatly with home furniture with classy look. This desk can be not only as a computer desk, but also served as a writing desk, a study desk, a vanity table or a makeup table, which is suitable for home and office use. Multipurpose desk adds function and style without overwhelming the space. Looks great in your living room of your home, office, bedroom or condo. It provides plenty of space for office work, studying, writing or gaming";
String wallmountedStudy =
    "The product is a wall mounted desk with display shelves .Made of 17 MM pre laminated particle wood board with natural wood grain finish. Open dimensions (L) 68 x (B) 56 x (H) 40 CM,Close dimensions (L) 68 x (B) 56x (H) 4 CM. Colour White Style wall mounted. Package Contents 1 Table with 1 books shelf unit. Product waranty one year in case of manufacturing defect. This product is quite easy to assemble, and you can do it or call a carpenter. All acessoried and assembly instruction is provided along with the product for your assist. If still you find any problem in installation you are free to contact";
String studychair1 =
    "Study Chair with Desklet Writing Pad is designed to provide comfort and functionality for all ages, making it ideal for students, professionals, and home office use. This versatile chair is built with a robust frame to ensure durability and long-lasting performance. It features a convenient desklet writing pad, perfect for taking notes, studying, or working on your laptop. The chair is fitted with a comfortable black cushion that provides excellent support during extended periods of sitting. Whether you're setting up a study space at home or need an efficient seating solution for a classroom or office, this Study Chair is designed to meet your needs with style and practicality.";
